kind: AIchorManifest
apiVersion: 0.2.3

builder:
  image: image
  dockerfile: ./Dockerfile
  context: .
  
spec:
  operator: jobset   
  image: image 
  command: "python3 -u main-dali.py" 
 
  tensorboard:
    enabled: false
  
  types:
    master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4
