kind: AIchorManifest
apiVersion: 0.2.3

builder:
  image: image
  dockerfile: ./Dockerfile
  context: .
  
spec:
  operator: pytorch
  restartPolicy:
    backoffLimit: 5
  image: image 
  command: "python3 -u main-dali.py --operator=jobset --sleep=300"
 
  tensorboard:
    enabled: false
  
  types:
    worker:
      count: 2
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
