kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ../../Dockerfile
  context: ../..
  
spec:
  operator: jobset   
  image: image 
  command: "python3 -u main-dali.py" 
 
  tensorboard:
    enabled: true
  #   usePVC:
  #     enabled: true
  #     name: "az-prjtb11-5de4098cb8b3459d-azpvc-1-d09842db6f6f4cc7"
  
  # storage:
  #   attachExistingPVCs:
  #     - name: "az-prjtb11-5de4098cb8b3459d-azpvc-1-d09842db6f6f4cc7"
  #       mountPoint: "/mnt/azpvcone"
  
  types:
    master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4 

    # worker-1:
    #   count: 1
    #   resources:
    #     cpus: 1
    #     ramRatio: 2
